##############################################################################
# The devices created below are essential to the page control automations
# and you'll probably want to carry them over to your own configuration
homeassistant:
  customize:
    input_number.hasp_kitchen_alarmcode1:
      hidden: true
    input_number.hasp_kitchen_alarmcode2:
      hidden: true
    input_number.hasp_kitchen_alarmcode3:
      hidden: true
    input_number.hasp_kitchen_alarmcode4:
      hidden: true

# Enable this iframe to integrate the HASP web admin panel in Hass.
# This will not work if you have SSL enabled, see details here:
# https://www.home-assistant.io/components/panel_iframe/
#
panel_iframe:
  kitchen:
    title: "kitchen"
    url: "http://kitchen"
    icon: "mdi:cellphone-text"

light:
  - platform: mqtt
    name: kitchen Backlight
    command_topic: "hasp/kitchen/light/switch"
    state_topic: "hasp/kitchen/light/state"
    brightness_state_topic: "hasp/kitchen/brightness/state"
    brightness_command_topic: "hasp/kitchen/brightness/set"
    availability_topic: "hasp/kitchen/status"
    payload_available: "ON"
    payload_not_available: "OFF"

binary_sensor:
  - platform: mqtt
    name: kitchen Connected
    device_class: connectivity
    state_topic: "hasp/kitchen/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/kitchen/status"
    payload_available: "ON"
    payload_not_available: "OFF"

sensor:
  - platform: mqtt
    name: kitchen Sensor
    state_topic: "hasp/kitchen/sensor"
    value_template: '{{ value_json.status }}'
    json_attributes:
      - espVersion
      - updateESPAvailable
      - lcdVersion
      - updateLcdAvailable
      - espUptime
      - signalStrength
      - haspIP

input_text:
  hasp_kitchen_pagebutton1label:
    name: kitchen Page 1 Label
    icon: mdi:book-open-page-variant
  hasp_kitchen_pagebutton2label:
    name: kitchen Page 2 Label
    icon: mdi:book-open-page-variant
  hasp_kitchen_pagebutton3label:
    name: kitchen Page 3 Label
    icon: mdi:book-open-page-variant

input_number:
  hasp_kitchen_pagebutton1page:
    name: kitchen Page 1 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_kitchen_pagebutton2page:
    name: kitchen Page 2 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_kitchen_pagebutton3page:
    name: kitchen Page 3 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_kitchen_activepage:
    name: kitchen Active Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_kitchen_alarmcode1:
    name: kitchen AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_kitchen_alarmcode2:
    name: kitchen AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_kitchen_alarmcode3:
    name: kitchen AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_kitchen_alarmcode4:
    name: kitchen AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

group:
  kitchen:
    name: kitchen
    view: yes
    entities:
      - binary_sensor.kitchen_connected
      - sensor.kitchen_sensor
      - light.kitchen_backlight
      - group.kitchen_pageselect
      - group.kitchen_colors
      - group.kitchen_automations
  kitchen_pageselect:
    name: kitchen Page Selection
    view: no
    entities:
      - input_number.hasp_kitchen_activepage
      - input_number.hasp_kitchen_pagebutton1page
      - input_text.hasp_kitchen_pagebutton1label
      - input_number.hasp_kitchen_pagebutton2page
      - input_text.hasp_kitchen_pagebutton2label
      - input_number.hasp_kitchen_pagebutton3page
      - input_text.hasp_kitchen_pagebutton3label
  kitchen_automations:
    name: kitchen automations
    view: no
    entities:
      - automation.hasp_kitchen_00_firsttimesetup

automation:
##############################################################################
# Run first time setup commands
  - alias: hasp_kitchen_00_FirstTimeSetup
    trigger: []
    action:
      - service: automation.trigger
        data:
          entity_id: 'automation.hasp_kitchen_00_automationgroupupdate'
      - service: homeassistant.turn_on
        data:
          entity_id: 'group.kitchen_automations'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_kitchen_pagebutton1label'
          value: 'scenes'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_kitchen_pagebutton2label'
          value: 'status'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_kitchen_pagebutton3label'
          value: 'lights'
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_pagebutton1page'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_pagebutton2page'
          value: 2
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_pagebutton3page'
          value: 3
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_activepage'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_selectedforegroundcolor'
          value: 0
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_selectedbackgroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_unselectedforegroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_kitchen_unselectedbackgroundcolor'
          value: 25388

##############################################################################
# Set automation group members on start - Thanks @Nightcat!
  - alias: hasp_kitchen_00_AutomationGroupUpdate
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: group.set
      data_template:
        object_id: "kitchen_automations"
        entities: >-
          {%- for item in states.automation if ((item.entity_id | lower).startswith('automation.hasp_kitchen_')) -%}
          {{ item.entity_id }}
          {% if not loop.last %}, {% endif %}
          {%- endfor -%}