##############################################################################
# Automations for handling Scene select buttons on page 1

automation:
  # Set font and text labels for scene buttons on device connection
  - alias: hasp_kitchen_p1_ScenesInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.kitchen_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[4].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[4].txt'
        payload: '"Open JPs"'
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[5].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[5].txt'
        payload: '"Close JPs"'
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[6].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[6].txt'
        payload: '"Open JMs"'
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[7].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[7].txt'
        payload: '"Close JMs"'

  # Trigger open JPs garage when p[1].b[4] pressed
  - alias: hasp_kitchen_p1_SceneButton4
    trigger:
    - platform: mqtt
      topic: 'hasp/kitchen/state/p[1].b[4]'
      payload: 'ON'
    action:
    - service: cover.open_cover
      entity_id: cover.jps_garage_door
      
#  # Trigger close jps garage when p[1].b[5] pressed
  - alias: hasp_kitchen_p1_SceneButton5
    trigger:
    - platform: mqtt
      topic: 'hasp/kitchen/state/p[1].b[5]'
      payload: 'ON'
    action:
    - service: cover.close_cover
      entity_id: cover.jps_garage_door

  # Trigger open justins garage when p[1].b[6] pressed
  - alias: hasp_kitchen_p1_SceneButton6
    trigger:
    - platform: mqtt
      topic: 'hasp/kitchen/state/p[1].b[6]'
      payload: 'ON'
    action:
    - service: cover.open_cover
      entity_id: cover.justins_garage_door

  # Trigger close justins garage when p[1].b[7] pressed
  - alias: hasp_kitchen_p1_SceneButton7
    trigger:
    - platform: mqtt
      topic: 'hasp/kitchen/state/p[1].b[7]'
      payload: 'ON'
    action:
    - service: cover.close_cover
      entity_id: cover.justins_garage_door

 # Toggle colors on p[3].b[4] (jps garage) if door is open make selected
  - alias: hasp_kitchen_p3_ToggleColor1
    trigger:
    - platform: state
      entity_id: cover.jps_garage_door
    - platform: state
      entity_id: 'binary_sensor.kitchen_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[4].bco'
        payload_template: >-
          {% if states.cover.jps_garage_door.state == "open" -%}
            {{ states.input_number.hasp_kitchen_unselectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/kitchen/command/p[1].b[4].pco'
        payload_template: >-
          {% if states.cover.jps_garage_door.state == "open" -%}
            {{ states.input_number.hasp_kitchen_unselectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedforegroundcolor.state | int }}
          {%- endif %}

# Toggle colors on p[3].b[5] (jps garage) if door is closed make selected
  - alias: hasp_kitchen_p3_ToggleColor2
    trigger:
    - platform: state
      entity_id: cover.jps_garage_door
    - platform: state
      entity_id: 'binary_sensor.kitchen_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[5].bco'
        payload_template: >-
          {% if states.cover.jps_garage_door.state == "closed" -%}
            {{ states.input_number.hasp_kitchen_unselectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/kitchen/command/p[1].b[5].pco'
        payload_template: >-
          {% if states.cover.jps_garage_door.state == "closed" -%}
            {{ states.input_number.hasp_kitchen_unselectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedforegroundcolor.state | int }}
          {%- endif %}

# Toggle colors on p[3].b[6] (justins garage) if door is open make selected
  - alias: hasp_kitchen_p3_ToggleColor3
    trigger:
    - platform: state
      entity_id: cover.justins_garage_door
    - platform: state
      entity_id: 'binary_sensor.kitchen_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[6].bco'
        payload_template: >-
          {% if states.cover.justins_garage_door.state == "open" -%}
            {{ states.input_number.hasp_kitchen_unselectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/kitchen/command/p[1].b[6].pco'
        payload_template: >-
          {% if states.cover.justins_garage_door.state == "open" -%}
            {{ states.input_number.hasp_kitchen_unselectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedforegroundcolor.state | int }}
          {%- endif %}

# Toggle colors on p[3].b[7] (justins garage) if door is closed make selected
  - alias: hasp_kitchen_p3_ToggleColor4
    trigger:
    - platform: state
      entity_id: cover.justins_garage_door
    - platform: state
      entity_id: 'binary_sensor.kitchen_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_kitchen_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/kitchen/command/p[1].b[7].bco'
        payload_template: >-
          {% if states.cover.justins_garage_door.state == "closed" -%}
            {{ states.input_number.hasp_kitchen_unselectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/kitchen/command/p[1].b[7].pco'
        payload_template: >-
          {% if states.cover.justins_garage_door.state == "closed" -%}
            {{ states.input_number.hasp_kitchen_unselectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_kitchen_selectedforegroundcolor.state | int }}
          {%- endif %}